import React from "react";
import { Grid } from "@mui/material";
import TableHistoryScreen from "./TableHistoryScreen";

export default function SavingHistoryScreen() {
  const worksheets = [
    {
      name: "Requisitos",
      columns: [
        { label: "Número de Comprobante", value: "receipt" },
        { label: "Cédula de Identidad", value: "cedulaIdentidad" },
        { label: "Tipo de Transacción", value: "tipoTransaccion" },
        { label: "Fecha", value: "fecha" },
        { label: "Valor de la Transacción", value: "valorTransaccion" },
        { label: "Saldo Final", value: "saldoFinal" },
        { label: "Tipo de Pago", value: "paymentType" },
        { label: "Observación", value: "observacion" },
      ],
      data: [
        {
          receipt: "18",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Depósito",
          fecha: "2021/05/25",
          valorTransaccion: "2743.40",
          saldoFinal: "2743.40",
          paymentType: "Transferencia",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "19",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Depósito",
          fecha: "2021/06/19",
          valorTransaccion: "7046.18",
          saldoFinal: "9786.58",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "20",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Retiro",
          fecha: "2021/06/22",
          valorTransaccion: "636.6",
          saldoFinal: "9152.98",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "22",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Depósito",
          fecha: "2021/07/05",
          valorTransaccion: "1680.69",
          saldoFinal: "10833.67",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "24",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Retiro",
          fecha: "2021/08/31",
          valorTransaccion: "4757.52",
          saldoFinal: "6076.15",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "26",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Depósito",
          fecha: "2021/09/20",
          valorTransaccion: "8938.69",
          saldoFinal: "15014.84",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "27",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Retiro",
          fecha: "2021/09/27",
          valorTransaccion: "8456.56",
          saldoFinal: "6558.28",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "28",
          cedulaIdentidad: "0625171348",
          tipoTransaccion: "Depósito",
          fecha: "2021/10/05",
          valorTransaccion: "9699.12",
          saldoFinal: "16257.40",
          paymentType: "Transferencia",
          observacion: "Añadir algún comentario relevante cliente 1",
        },
        {
          receipt: "39",
          cedulaIdentidad: "0312369195",
          tipoTransaccion: "Depósito",
          fecha: "2022/05/22",
          valorTransaccion: "5459.73",
          saldoFinal: "5459.73",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 2",
        },
        {
          receipt: "1",
          cedulaIdentidad: "1494915895",
          tipoTransaccion: "Depósito",
          fecha: "2019/04/26",
          valorTransaccion: "6928.07",
          saldoFinal: "6928.07",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 3",
        },
        {
          receipt: "2",
          cedulaIdentidad: "1494915895",
          tipoTransaccion: "Depósito",
          fecha: "2019/06/14",
          valorTransaccion: "8748.08",
          saldoFinal: "15676.15",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 3",
        },
        {
          receipt: "3",
          cedulaIdentidad: "1494915895",
          tipoTransaccion: "Depósito",
          fecha: "2019/07/31",
          valorTransaccion: "6014.19",
          saldoFinal: "21690.34",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 3",
        },
        {
          receipt: "4",
          cedulaIdentidad: "1494915895",
          tipoTransaccion: "Depósito",
          fecha: "2019/09/11",
          valorTransaccion: "8536.91",
          saldoFinal: "30227.25",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 3",
        },
        {
          receipt: "5",
          cedulaIdentidad: "1494915895",
          tipoTransaccion: "Depósito",
          fecha: "2019/09/23",
          valorTransaccion: "1324.04",
          saldoFinal: "31551.29",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 3",
        },
        {
          receipt: "9",
          cedulaIdentidad: "1494915895",
          tipoTransaccion: "Depósito",
          fecha: "2020/03/29",
          valorTransaccion: "4224.95",
          saldoFinal: "35776.24",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 3",
        },
        {
          receipt: "10",
          cedulaIdentidad: "1494915895",
          tipoTransaccion: "Depósito",
          fecha: "2020/08/19",
          valorTransaccion: "9268.88",
          saldoFinal: "45045.12",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 3",
        },
        {
          receipt: "6",
          cedulaIdentidad: "0890686433",
          tipoTransaccion: "Depósito",
          fecha: "2019/11/07",
          valorTransaccion: "4595.89",
          saldoFinal: "4595.89",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 4",
        },
        {
          receipt: "7",
          cedulaIdentidad: "0890686433",
          tipoTransaccion: "Retiro",
          fecha: "2019/11/18",
          valorTransaccion: "1812.89",
          saldoFinal: "2783.00",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 4",
        },
        {
          receipt: "8",
          cedulaIdentidad: "0890686433",
          tipoTransaccion: "Depósito",
          fecha: "2020/03/08",
          valorTransaccion: "1251.32",
          saldoFinal: "4034.32",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 4",
        },
        {
          receipt: "11",
          cedulaIdentidad: "0890686433",
          tipoTransaccion: "Depósito",
          fecha: "2020/09/26",
          valorTransaccion: "9298.32",
          saldoFinal: "13332.64",
          paymentType: "Transferencia",
          observacion: "Añadir algún comentario relevante cliente 4",
        },
        {
          receipt: "12",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Depósito",
          fecha: "2020/11/18",
          valorTransaccion: "5337.14",
          saldoFinal: "5337.14",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "13",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Retiro",
          fecha: "2020/12/25",
          valorTransaccion: "3052.04",
          saldoFinal: "2285.10",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "14",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Depósito",
          fecha: "2021/01/07",
          valorTransaccion: "4933.60",
          saldoFinal: "7218.70",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "15",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Depósito",
          fecha: "2021/02/04",
          valorTransaccion: "1826.92",
          saldoFinal: "9045.62",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "16",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Retiro",
          fecha: "2021/03/28",
          valorTransaccion: "4136.36",
          saldoFinal: "4909.26",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "17",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Depósito",
          fecha: "2021/05/15",
          valorTransaccion: "3196.49",
          saldoFinal: "8105.75",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "21",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Retiro",
          fecha: "2021/06/27",
          valorTransaccion: "1899.59",
          saldoFinal: "6206.16",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "23",
          cedulaIdentidad: "0442418679",
          tipoTransaccion: "Retiro",
          fecha: "2021/08/03",
          valorTransaccion: "3081.42",
          saldoFinal: "3124.74",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 5",
        },
        {
          receipt: "32",
          cedulaIdentidad: "0616029916",
          tipoTransaccion: "Depósito",
          fecha: "2022/04/25",
          valorTransaccion: "1107.30",
          saldoFinal: "1107.30",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 6",
        },
        {
          receipt: "33",
          cedulaIdentidad: "0616029916",
          tipoTransaccion: "Depósito",
          fecha: "2022/04/29",
          valorTransaccion: "7955.13",
          saldoFinal: "9062.43",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 6",
        },
        {
          receipt: "34",
          cedulaIdentidad: "0616029916",
          tipoTransaccion: "Retiro",
          fecha: "2022/04/29",
          valorTransaccion: "2404.59",
          saldoFinal: "6657.87",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 6",
        },
        {
          receipt: "35",
          cedulaIdentidad: "0616029916",
          tipoTransaccion: "Depósito",
          fecha: "2022/05/04",
          valorTransaccion: "2361.88",
          saldoFinal: "9019.75",
          paymentType: "Cheque",
          observacion: "Añadir algún comentario relevante cliente 6",
        },
        {
          receipt: "36",
          cedulaIdentidad: "0616029916",
          tipoTransaccion: "Depósito",
          fecha: "2022/05/08",
          valorTransaccion: "4695.20",
          saldoFinal: "13714.95",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 6",
        },
        {
          receipt: "37",
          cedulaIdentidad: "0616029916",
          tipoTransaccion: "Retiro",
          fecha: "2022/05/12",
          valorTransaccion: "235.60",
          saldoFinal: "13479.35",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 6",
        },
        {
          receipt: "38",
          cedulaIdentidad: "0616029916",
          tipoTransaccion: "Depósito",
          fecha: "2022/05/16",
          valorTransaccion: "8842.64",
          saldoFinal: "22321.99",
          paymentType: "Transferencia",
          observacion: "Añadir algún comentario relevante cliente 6",
        },
        {
          receipt: "25",
          cedulaIdentidad: "0256515652",
          tipoTransaccion: "Depósito",
          fecha: "2021/09/19",
          valorTransaccion: "3980.58",
          saldoFinal: "3980.58",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 7",
        },
        {
          receipt: "29",
          cedulaIdentidad: "0256515652",
          tipoTransaccion: "Retiro",
          fecha: "2021/11/19",
          valorTransaccion: "1671.39",
          saldoFinal: "2309.19",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 7",
        },
        {
          receipt: "30",
          cedulaIdentidad: "0256515652",
          tipoTransaccion: "Depósito",
          fecha: "2021/12/15",
          valorTransaccion: "3824.56",
          saldoFinal: "6133.75",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 7",
        },
        {
          receipt: "31",
          cedulaIdentidad: "0256515652",
          tipoTransaccion: "Retiro",
          fecha: "2022/02/25",
          valorTransaccion: "2108.39",
          saldoFinal: "4025.36",
          paymentType: "Efectivo",
          observacion: "Añadir algún comentario relevante cliente 7",
        },
      ],
    },
  ];

  return (
    <Grid container>
      <Grid item xs={12}>
        <TableHistoryScreen worksheets={worksheets} />
      </Grid>
    </Grid>
  );
}
