import React from "react";
import { Grid } from "@mui/material";
import TableClientsScreen from "./TableClientsScreen";

export default function UploadClientsScreen() {
  const worksheets = [
    {
      name: "Requisitos",
      columns: [
        { label: "Nombres", value: "nombres" },
        { label: "Apellidos", value: "apellidos" },
        { label: "Cédula de Identidad", value: "cedulaIdentidad" },
        { label: "Número de Teléfono", value: "numeroTelefono" },
        { label: "2do Número de Teléfono", value: "numeroTelefono2" },
        { label: "Tarifa", value: "tarifa" },
        { label: "Estado Civil", value: "estadoCivil" },
        { label: "Fecha de Nacimiento", value: "fechaNacimiento" },
        { label: "Fecha de Creación", value: "fechaCreacion" },
        { label: "Dirección", value: "direccion" },
        { label: "Email", value: "email" },
        { label: "Nombres del Conyugue", value: "nombresConyugue" },
        { label: "Apellidos del Conyugue", value: "apellidosConyugue" },
        { label: "CI del Conyugue", value: "cedulaIdentidadConyugue" },
        { label: "Teléfono del Conyugue", value: "telefonoConyugue" },
        { label: "Parentesco", value: "parentesco" },
        { label: "Nombres del Parentesco", value: "nombresParentesco" },
        { label: "Apellidos del Parentesco", value: "apellidosParentesco" },
        { label: "CI del Parentesco", value: "cedulaIdentidadParentesco" },
        { label: "Teléfono del Parentesco", value: "telefonoParentesco" },
      ],
      data: [
        {
          nombres: "Augustine Irvine",
          apellidos: "Jiracek Greatrakes",
          cedulaIdentidad: "0738209846",
          numeroTelefono: "0980010641",
          numeroTelefono2: "028862805",
          tarifa: "Socio",
          estadoCivil: "Unión Libre",
          fechaNacimiento: "1957/02/18",
          fechaCreacion: "2019/12/15",
          direccion: "3890 Vidon Alley",
          email: "rglassardt@cocolog-nifty.com",
          nombresConyugue: "Curry Thebault",
          apellidosConyugue: "Merrigan Mooring",
          cedulaIdentidadConyugue: "2101197238",
          telefonoConyugue: "0948424818",
          parentesco: "Nuera",
          nombresParentesco: "Dorri Flem",
          apellidosParentesco: "Marchelli Upham",
          cedulaIdentidadParentesco: "0798481971",
          telefonoParentesco: "0936668162",
        },
        {
          nombres: "Fannie Joseito",
          apellidos: "Conti Scruby",
          cedulaIdentidad: "0766842405",
          numeroTelefono: "0947059385",
          numeroTelefono2: "0941225815",
          tarifa: "Socio",
          estadoCivil: "Viudo/a",
          fechaNacimiento: "1958/01/23",
          fechaCreacion: "2021/11/08",
          direccion: "58 Meadow Valley Hill",
          email: "njeremiah22@shutterfly.com",
          nombresConyugue: "",
          apellidosConyugue: "",
          cedulaIdentidadConyugue: "",
          telefonoConyugue: "",
          parentesco: "Sobrina",
          nombresParentesco: "Deana Ella",
          apellidosParentesco: "Domencs Josefs",
          cedulaIdentidadParentesco: "0777185000",
          telefonoParentesco: "0978852836",
        },
        {
          nombres: "Darrelle Loreen",
          apellidos: "Helian Philippard",
          cedulaIdentidad: "0151729509",
          numeroTelefono: "0932011685",
          numeroTelefono2: "",
          tarifa: "Particular",
          estadoCivil: "Soltero/a",
          fechaNacimiento: "1999/10/09",
          fechaCreacion: "2020/07/16",
          direccion: "63685 Doe Crossing Lane",
          email: "omalkin1@comsenz.com",
          nombresConyugue: "",
          apellidosConyugue: "",
          cedulaIdentidadConyugue: "",
          telefonoConyugue: "",
          parentesco: "Abuelo",
          nombresParentesco: "Shani Errick",
          apellidosParentesco: "Helian Van Weedenburg",
          cedulaIdentidadParentesco: "0107905992",
          telefonoParentesco: "0914310693",
        },
        {
          nombres: "Granny Alberto",
          apellidos: "Arniz Yarham",
          cedulaIdentidad: "0325406544",
          numeroTelefono: "0998869069",
          numeroTelefono2: "078311794",
          tarifa: "Socio",
          estadoCivil: "Casado/a",
          fechaNacimiento: "1970/01/22",
          fechaCreacion: "2022/02/03",
          direccion: "59535 Vernon Street",
          email: "alearned1i@unesco.org",
          nombresConyugue: "Annamaria Mata",
          apellidosConyugue: "Neilson Glynn",
          cedulaIdentidadConyugue: "2161057099",
          telefonoConyugue: "0986736206",
          parentesco: "Suegra",
          nombresParentesco: "Dancy Pavia",
          apellidosParentesco: "Glynn Armit",
          cedulaIdentidadParentesco: "0390884755",
          telefonoParentesco: "0988666077",
        },
        {
          nombres: "Terrance Felicle",
          apellidos: "Poletto Blaasch",
          cedulaIdentidad: "1878365057",
          numeroTelefono: "0933513745",
          numeroTelefono2: "062892949",
          tarifa: "Particular",
          estadoCivil: "Viudo/a",
          fechaNacimiento: "1970/04/07",
          fechaCreacion: "2019/08/30",
          direccion: "1 Donald Alley",
          email: "tcoleman2p@buzzfeed.com",
          nombresConyugue: "",
          apellidosConyugue: "",
          cedulaIdentidadConyugue: "",
          telefonoConyugue: "",
          parentesco: "Abuela",
          nombresParentesco: "Tallie Berta",
          apellidosParentesco: "Simonsson Parkes",
          cedulaIdentidadParentesco: "1842643379",
          telefonoParentesco: "0932452346",
        },
        {
          nombres: "Mendel Raddy",
          apellidos: "Bozier Lassey",
          cedulaIdentidad: "1515482409",
          numeroTelefono: "0980112269",
          numeroTelefono2: "",
          tarifa: "Particular",
          estadoCivil: "Soltero/a",
          fechaNacimiento: "1967/03/06",
          fechaCreacion: "2019/01/03",
          direccion: "94 Ridgeway Trail",
          email: "abridglandu@twitter.com",
          nombresConyugue: "",
          apellidosConyugue: "",
          cedulaIdentidadConyugue: "",
          telefonoConyugue: "",
          parentesco: "Madre",
          nombresParentesco: "Imogen Enrichetta",
          apellidosParentesco: "Lassey Sibson",
          cedulaIdentidadParentesco: "1503890749",
          telefonoParentesco: "0940383088",
        },
        {
          nombres: "Saleem Tandie",
          apellidos: "Colebrook Ollerenshaw",
          cedulaIdentidad: "0149027802",
          numeroTelefono: "0947388994",
          numeroTelefono2: "",
          tarifa: "Socio",
          estadoCivil: "Soltero/a",
          fechaNacimiento: "1996/02/17",
          fechaCreacion: "2020/12/03",
          direccion: "47458 Hermina Plaza",
          email: "kchoupind@scribd.com",
          nombresConyugue: "",
          apellidosConyugue: "",
          cedulaIdentidadConyugue: "",
          telefonoConyugue: "",
          parentesco: "Sobrino",
          nombresParentesco: "Ruggiero Hasheem",
          apellidosParentesco: "Behninck Caney",
          cedulaIdentidadParentesco: "0152961511",
          telefonoParentesco: "0945468843",
        },
      ],
    },
  ];

  return (
    <Grid container>
      <Grid item xs={12}>
        <TableClientsScreen worksheets={worksheets} />
      </Grid>
    </Grid>
  );
}
