import { Grid } from "@mui/material";
import React from "react";
import TableCreditScreen from "./TableCreditScreen";

export default function UploadCreditScreen() {
  const worksheets = [
    {
      name: "Requisitos",
      columns: [
        { label: "Carpeta", value: "folder" },
        { label: "Número de Cuota", value: "quotaNumber" },
        { label: "Fecha de Pago", value: "paymentDate" },
        { label: "Interés Periodo", value: "interest" },
        { label: "Capital Amortizado", value: "amortizedCapital" },
        { label: "Fondo de Desgravamen", value: "desgravamen" },
        { label: "Valor Cuota", value: "quotaValue" },
        { label: "Saldo Remanente", value: "remainingBalance" },
        { label: "Tipo de Pago", value: "paymentType" },
        { label: "Estado", value: "status" },
      ],
      data: [
        {
          folder: "001",
          quotaNumber: "1",
          paymentDate: "2021/08/16",
          interest: "25.00",
          amortizedCapital: "72.49",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "927.51",
          paymentType: "EFECTIVO",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "2",
          paymentDate: "2021/09/16",
          interest: "23.19",
          amortizedCapital: "74.30",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "853.21",
          paymentType: "EFECTIVO",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "3",
          paymentDate: "2021/10/16",
          interest: "21.33",
          amortizedCapital: "76.16",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "777.06",
          paymentType: "EFECTIVO",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "4",
          paymentDate: "2021/11/16",
          interest: "19.43",
          amortizedCapital: "78.06",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "699.00",
          paymentType: "EFECTIVO",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "5",
          paymentDate: "2021/12/16",
          interest: "17.47",
          amortizedCapital: "80.01",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "618.98",
          paymentType: "CHEQUE",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "6",
          paymentDate: "2022/01/16",
          interest: "15.47",
          amortizedCapital: "82.01",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "536.97",
          paymentType: "CHEQUE",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "7",
          paymentDate: "2022/02/16",
          interest: "13.42",
          amortizedCapital: "84.06",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "452.91",
          paymentType: "CHEQUE",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "8",
          paymentDate: "2022/03/16",
          interest: "11.32",
          amortizedCapital: "86.16",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "366.74",
          paymentType: "CHEQUE",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "9",
          paymentDate: "2022/04/16",
          interest: "9.17",
          amortizedCapital: "88.32",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "278.43",
          paymentType: "TRANSFERENCIA",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "10",
          paymentDate: "2022/05/16",
          interest: "6.96",
          amortizedCapital: "90.53",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "187.90",
          paymentType: "TRANSFERENCIA",
          status: "PAGADO",
        },
        {
          folder: "001",
          quotaNumber: "11",
          paymentDate: "2022/06/16",
          interest: "4.70",
          amortizedCapital: "92.79",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "95.11",
          paymentType: "NULL",
          status: "PENDIENTE",
        },
        {
          folder: "001",
          quotaNumber: "12",
          paymentDate: "2022/07/16",
          interest: "2.38",
          amortizedCapital: "95.11",
          desgravamen: "0.83",
          quotaValue: "98.32",
          remainingBalance: "0.00",
          paymentType: "NULL",
          status: "PENDIENTE",
        },
      ],
    },
  ];

  return (
    <Grid container>
      <Grid item xs={12}>
        <TableCreditScreen worksheets={worksheets} />
      </Grid>
    </Grid>
  );
}
